import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Text,
  Box,
  Image,
  Button,
  Container,
  UnorderedList,
  ListItem,
  Grid,
  SimpleGrid,
  Divider,
  Toast,
  useToast,
} from "@chakra-ui/react";
import axios from "axios";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AiFillWechat } from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });
const getFromLocalStorage = (key: string) => {
  if (!key || typeof window === "undefined") {
    return "";
  }
  return localStorage.getItem(key);
};

export default function Home() {
  const initialState = {
    user: getFromLocalStorage("userData")
      ? JSON.parse(getFromLocalStorage("userData") || "{}")
      : [],
  };
  const toast=useToast()
  const [data, setData] = useState([]);
  const [category, setCategory] = useState("all");
  const user = initialState.user;
  const [username, setUsername] = useState(user.username || "");
  // const username = user.username || "";

  const getData = (category: string) => {
    if (category !== "all") {
      // console.log(category)
      axios
        .get(
          `https://fancy-gray-lion.cyclic.app/combined/filter?category=${category}`
        )
        .then((data) => setData(data.data.combineddata))
        .catch((err) => console.log(err));
    } else {
      axios
        .get(`https://fancy-gray-lion.cyclic.app/combined`)
        .then((data) => setData(data.data.combineddata))
        .catch((err) => console.log(err));
    }
  };
  useEffect(() => {
    getData(category);
  }, [category]);

  const logoutuser = () => {
    localStorage.clear();
    setUsername("");
    
    toast({
      title: " Logout Successfully",
      description: "Please Login ",
      status: "success",
      duration: 9000,
      isClosable: true,
    });
  };
  return (
    <>
      <Head>
        <title>LearningPlate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://i.postimg.cc/jqWWx3m2/learningplate.png"
        />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Box className={styles.navbar}>
            <Box className={styles.navbarimage}>
              <Image
                src="https://i.postimg.cc/jqWWx3m2/learningplate.png"
                alt="learningplate"
              />
            </Box>
            <Box className={styles.loginbutton}>
              {username === "" ? (
                <Link href="/Login">
                  <Button>Login</Button>
                </Link>
              ) : (
                <Button>{username}</Button>
              )}

              {username === "" ? (
                <Link href="/Signup">
                  {" "}
                  <Button>Register</Button>
                </Link>
              ) : (
                <Button onClick={logoutuser}>Logout</Button>
              )}
            </Box>
          </Box>
          <Box className={styles.deliver}>
            <Box className={styles.data}>
              <Text as="h1">
                Deliver inspiring learning experiences{" "}
                <strong>on any scale.</strong>
              </Text>
              <Text>
                Enable online campuses, instructor-led courses, degree programs,
                and self-paced courses using a single platform.
              </Text>
            </Box>
            <Box className={styles.dataimage}>
              <Image
                src="https://openedx.org/wp-content/uploads/2018/12/Home-header.svg"
                alt="images"
              />
            </Box>
          </Box>
          <Box className={styles.trusted}>
            <Box>
              <Text as="h2">Trusted by top organizations worldwide.</Text>
              <figure>
                <UnorderedList>
                  <ListItem>
                    <Image
                      src="https://openedx.org/wp-content/uploads/2019/01/logo_ibm.png"
                      alt="image2"
                    />
                  </ListItem>
                  <ListItem>
                    <Image
                      src="https://openedx.org/wp-content/uploads/2019/01/logo_microsoft.png"
                      alt="image2"
                    />
                  </ListItem>
                  <ListItem>
                    <Image
                      src="https://openedx.org/wp-content/uploads/2019/01/logo_mit.png"
                      alt="image2"
                    />
                  </ListItem>
                  <ListItem>
                    <Image
                      src="https://openedx.org/wp-content/uploads/2019/01/logo_harvard.png"
                      alt="image2"
                    />
                  </ListItem>
                  <ListItem>
                    <Image
                      src="https://openedx.org/wp-content/uploads/2019/01/logo_xuetangx.png"
                      alt="image2"
                    />
                  </ListItem>
                </UnorderedList>
              </figure>
            </Box>
          </Box>
          <Text as="h3" className={styles.texth3}>
            Easily and confidently scale from supporting small learning to{" "}
            <strong>thousands of simultaneous learners.</strong>
          </Text>

          <Box className={styles.instructors}>
            <Box>
              <Container className={styles.instructorsleft}>
                <Text as="h3">Empower learners and instructors</Text>
                <UnorderedList>
                  <ListItem>
                    Interactive forums and discussions with IA
                  </ListItem>
                  <ListItem>Advance learners and Instructor</ListItem>
                  <ListItem>Live video conferencing</ListItem>
                </UnorderedList>
              </Container>

              <Container className={styles.instructorsleft}>
                <Text as="h3">Cross platform</Text>
                <UnorderedList>
                  <ListItem>Work on any device</ListItem>
                  <ListItem>
                    Seamlessly integrates with third part tools
                  </ListItem>
                </UnorderedList>
              </Container>

              <Container className={styles.instructorsleft}>
                <Text as="h3">Extensible and inclusive</Text>
                <UnorderedList>
                  <ListItem>Easy to use our platform</ListItem>
                  <ListItem>Working on new project after end of units</ListItem>
                  <ListItem>
                    Connecting with high professionals teacher
                  </ListItem>
                </UnorderedList>
              </Container>
            </Box>
            <Box className={styles.instructorsimage}>
              <Image
                src="https://i.postimg.cc/9fbdr6rs/get-with-open-edx.png"
                alt="empower image"
              />
            </Box>
          </Box>
          <Text className={styles.new}>
            <span className={styles.new1}>New</span>on learningplate
          </Text>
          <Box className={styles.buttons}>
            <Button onClick={() => setCategory("ai")}>
              Artificial Intelligence{" "}
            </Button>
            <Button onClick={() => setCategory("business")}>Business</Button>
            <Button onClick={() => setCategory("datascience")}>
              {" "}
              Data Science
            </Button>
            <Button onClick={() => setCategory("webdevelopment")}>
              Web Development
            </Button>
          </Box>
          <Box
            w={"90%"}
            mx={"auto"}
            pt={5}
            px={{ base: 2, sm: 12, md: 17 }}
            mb={20}
          >
            <Divider />
            <SimpleGrid>
              {/* <Link href="/SinglePage"> */}
              <Grid className={styles.grids}>
                {/* <Link href="/SinglePage" > */}
                {/* <Grid  xs={2} sm={4} md={4} > */}
                {data.map((el) => (
                  <Link key={el._id} href={`/SinglePage/${el._id}`}>
                    <Box
                      borderRadius={"30px"}
                      boxShadow={
                        "rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(0, 0, 0, 0.09) 0px -3px 5px"
                      }
                      textAlign="center"
                      style={{
                        padding: "25px 1px",
                      }}
                    >
                      <Image
                        h={{
                          base: "240px",
                          sm: "200px",
                          md: "250px",
                          lg: "270px",
                          xl: "300px",
                        }}
                        src={el.imgurl}
                        alt={el.title}
                      />
                      <Text
                        style={{
                          fontWeight: 600,
                          color: "#212121",
                        }}
                      >
                        {el.title}
                      </Text>
                      <Text
                        style={{
                          color: "green",
                        }}
                      >
                        {el.university}
                      </Text>
                    </Box>
                  </Link>
                ))}
              </Grid>
              {/* </Link> */}
            </SimpleGrid>
          </Box>
          <Link href="/Chat">
            <button className={styles.chatbox}>
              <AiFillWechat size={35} />
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
