import React, { useState } from "react";

import Head from "next/head";

import {
  Box,
  Button,
  FormControl,
  FormErrorMessage,
  Input,
  Select,
  Stack,
  Image,
  Text,
  useToast,
} from "@chakra-ui/react";
import Styles from "@/styles/Login.module.css";
import axios from "axios";
import Link from "next/link";
import { useRouter } from "next/router";
const Login = () => {
  const toast = useToast();
  const router = useRouter();
  const [islogin, setlogin] = useState(false);
  const [input, setInput] = useState({
    username: "",
    password: "",
  });
  const [isError, setError] = useState({
    username: false,
    password: false,
  });
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setInput({ ...input, [name]: value });
  };
  const handleError = () => {
    setError({
      ...isError,
      username: input.username === "",
      password: input.password === "",
    });
    if (input.username!=="" && input.password!=="") {
      CloseBox();
    }
  };

  const CloseBox = () => {
    if (!isError.username && !isError.password) {
      //Send Post request for add new address
      // onClick(false);
      LoginData();
    }
  };
  const LoginData = async () => {
    try {
      let res = await axios.post(
        "https://fancy-gray-lion.cyclic.app/login",
        input
      );
      localStorage.setItem("userData",JSON.stringify(res.data.user));
      toast({
        title: "Successfully Login",
        description: "Welcome to Learning Plate ",
        status: "success",
        duration: 9000,
        isClosable: true,
      });
      setlogin(true);
     
  router.push('/')

    } catch (err) {
      setlogin(false);
      console.log(err);
    }
  };
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://i.postimg.cc/jqWWx3m2/learningplate.png"
        />
      </Head>
      <main id={Styles.main}>
        <Box className={Styles.navbarimage}>
          <Link href="/">
          <Image
            src="https://i.postimg.cc/jqWWx3m2/learningplate.png"
            alt="learningplate"
          /></Link>
        </Box>
        <Box className={Styles.bg}>
          <Box className={Styles.images}>
            <Image
              src="https://cdn.dribbble.com/users/2234430/screenshots/8587843/media/5a7b6b3be7edd17ae98a25d010277e62.gif"
              alt="login"
            />
          </Box>
          <Stack className={Styles.form} spacing={6}>
            <Text
              as="h1"
              style={{
                textAlign: "center",
                fontSize: "32px",
                fontWeight: 600,
                color: "white",
              }}
            >
              Login
            </Text>
            <Box>
              <FormControl isRequired isInvalid={isError.username}>
                <Input
                  name="username"
                  onChange={handleInputChange}
                  value={input.username}
                  placeholder="username"
                />
                {isError.username && (
                  <FormErrorMessage color="red">
                    Enter your username
                  </FormErrorMessage>
                )}
              </FormControl>
            </Box>
            <Box display="flex">
              <FormControl isInvalid={isError.password} isRequired>
                <Input
                  type="password"
                  name="password"
                  onChange={handleInputChange}
                  value={input.password}
                  placeholder="Password"
                />
                {isError.password && (
                  <FormErrorMessage color="red">
                    Enter Password
                  </FormErrorMessage>
                )}
              </FormControl>
            </Box>
            <Box className={Styles.btn}>
            <Button
              colorScheme="white"
              bg="rgb(0, 181, 181)"
              onClick={handleError}
              >
              Login
              </Button>
              <Link href="/Signup">
            <Button
              colorScheme="white"
              bg="rgb(0, 181, 181)"
              >
              Create Account
            </Button></Link>
                </Box>
          </Stack>
        </Box>
      </main>
    </>
  );
};
export default Login;
